library(plyr)
library(xlsx)
library(tcltk)
library(progress)
library(plyr)
library(magrittr)  
library(mice)      #处理缺失值
library(xts)
library(rJava)
library(xlsxjars)

f17<-read.csv("c:/users/lenovo/desktop/BALL/JSM投稿/data and code/final17.csv")
# names(f17)
# f16s<-f16[,c(2,3,22,58)]
#  head(f16s)

 
# name<-read.csv("c:/users/lenovo/desktop/BALL/JSM投稿/data and code/f17.csv")
# 
# #替换team
# a<-paste("f16s$team1<-gsub(\"",name$team17,"\",\"",name$team,"\",f16s$team1)",sep="")%>%as.data.frame()
# b<-paste("f16s$pk<-gsub(\"",name$team17,"\",\"",name$team,"\",f16s$pk)",sep="")%>%as.data.frame()
# c<-paste("f16s$vs_team<-gsub(\"",name$team17,"\",\"",name$team,"\",f16s$vs_team)",sep="")%>%as.data.frame()
# #替换人名
# d<-paste("f16s$player<-gsub(\"",name$player17,"\",\"",name$player,"\",f16s$player)",sep="")%>%as.data.frame()
# 
# e<-rbind(a,b,c,d)
# write.csv(e,"c:/users/lenovo/desktop/BALL/JSM投稿/data and code/Eng_N_17.csv")
 
 f17$team<-gsub("小牛","Mavericks",f17$team)
 f17$team<-gsub("独行侠","Mavericks",f17$team)
 f17$team<-gsub("黄蜂","Hornets",f17$team)
 f17$team<-gsub("七六人","76ers",f17$team)
 f17$team<-gsub("尼克斯","Knicks",f17$team)
 f17$team<-gsub("奇才","Wizards",f17$team)
 f17$team<-gsub("火箭","Rockets",f17$team)
 f17$team<-gsub("热火","Heat",f17$team)
 
 f17$team<-gsub("湖人","Lakers",f17$team)
 f17$team<-gsub("凯尔特","Celtics",f17$team)
 f17$team<-gsub("太阳","Suns",f17$team)
 f17$team<-gsub("森林狼","Timberwolves",f17$team)
 f17$team<-gsub("鹈鹕","Pelicans",f17$team)
 f17$team<-gsub("掘金","Nuggets",f17$team)
 f17$team<-gsub("太阳","Suns",f17$team)
 f17$team<-gsub("猛龙","Raptors",f17$team)
 f17$team<-gsub("雄鹿","Bucks",f17$team)
 f17$team<-gsub("雷霆","Thunder",f17$team)
 f17$team<-gsub("老鹰","Hawks",f17$team)
 f17$team<-gsub("国王","Kings",f17$team)
 f17$team<-gsub("公牛","Bulls",f17$team)
 f17$team<-gsub("掘金","Nuggets",f17$team)
 f17$team<-gsub("灰熊","Grizzlies",f17$team)
 f17$team<-gsub("活塞","Pistons",f17$team)
 f17$team<-gsub("掘金","Nuggets",f17$team)
 f17$team<-gsub("篮网","Nets",f17$team)
 f17$team<-gsub("老鹰","Hawks",f17$team)
 f17$team<-gsub("76人","76ers",f17$team)
 f17$team<-gsub("快船","Clippers",f17$team)
 f17$team<-gsub("猛龙","Raptors",f17$team)
 f17$team<-gsub("国王","Kings",f17$team)
 f17$team<-gsub("马刺","Spurs",f17$team)
 f17$team<-gsub("灰熊","Grizzlies",f17$team)
 f17$team<-gsub("湖人","Lakers",f17$team)
 f17$team<-gsub("太阳","Suns",f17$team)
 f17$team<-gsub("雄鹿","Bucks",f17$team)
 f17$team<-gsub("勇士","Warriors",f17$team)
 f17$team<-gsub("快船","Clippers",f17$team)
 f17$team<-gsub("魔术","Magic",f17$team)
 f17$team<-gsub("篮网","Nets",f17$team)
 f17$team<-gsub("凯尔特","Celtics",f17$team)
 f17$team<-gsub("开拓者","Blazers",f17$team)
 f17$team<-gsub("公牛","Bulls",f17$team)
 f17$team<-gsub("活塞","Pistons",f17$team)
 f17$team<-gsub("步行者","Pacers",f17$team)
 f17$team<-gsub("爵士","Jazz",f17$team)
 f17$team<-gsub("骑士","Cavaliers",f17$team)
 f17$team<-gsub("[\u4e00-\u9fa5]","",f17$team)
 
 f17$pk<-gsub("小牛","Mavericks",f17$pk)
 f17$pk<-gsub("独行侠","Mavericks",f17$pk)
 f17$pk<-gsub("黄蜂","Hornets",f17$pk)
 f17$pk<-gsub("七六人","76ers",f17$pk)
 f17$pk<-gsub("尼克斯","Knicks",f17$pk)
 f17$pk<-gsub("奇才","Wizards",f17$pk)
 f17$pk<-gsub("火箭","Rockets",f17$pk)
 f17$pk<-gsub("热火","Heat",f17$pk)
 
 f17$pk<-gsub("湖人","Lakers",f17$pk)
 f17$pk<-gsub("凯尔特","Celtics",f17$pk)
 f17$pk<-gsub("太阳","Suns",f17$pk)
 f17$pk<-gsub("森林狼","Timberwolves",f17$pk)
 f17$pk<-gsub("鹈鹕","Pelicans",f17$pk)
 f17$pk<-gsub("掘金","Nuggets",f17$pk)
 f17$pk<-gsub("太阳","Suns",f17$pk)
 f17$pk<-gsub("猛龙","Raptors",f17$pk)
 f17$pk<-gsub("雄鹿","Bucks",f17$pk)
 f17$pk<-gsub("雷霆","Thunder",f17$pk)
 f17$pk<-gsub("老鹰","Hawks",f17$pk)
 f17$pk<-gsub("国王","Kings",f17$pk)
 f17$pk<-gsub("公牛","Bulls",f17$pk)
 f17$pk<-gsub("掘金","Nuggets",f17$pk)
 f17$pk<-gsub("灰熊","Grizzlies",f17$pk)
 f17$pk<-gsub("活塞","Pistons",f17$pk)
 f17$pk<-gsub("掘金","Nuggets",f17$pk)
 f17$pk<-gsub("篮网","Nets",f17$pk)
 f17$pk<-gsub("老鹰","Hawks",f17$pk)
 f17$pk<-gsub("76人","76ers",f17$pk)
 f17$pk<-gsub("快船","Clippers",f17$pk)
 f17$pk<-gsub("猛龙","Raptors",f17$pk)
 f17$pk<-gsub("国王","Kings",f17$pk)
 f17$pk<-gsub("马刺","Spurs",f17$pk)
 f17$pk<-gsub("灰熊","Grizzlies",f17$pk)
 f17$pk<-gsub("湖人","Lakers",f17$pk)
 f17$pk<-gsub("太阳","Suns",f17$pk)
 f17$pk<-gsub("雄鹿","Bucks",f17$pk)
 f17$pk<-gsub("勇士","Warriors",f17$pk)
 f17$pk<-gsub("快船","Clippers",f17$pk)
 f17$pk<-gsub("魔术","Magic",f17$pk)
 f17$pk<-gsub("篮网","Nets",f17$pk)
 f17$pk<-gsub("凯尔特","Celtics",f17$pk)
 f17$pk<-gsub("开拓者","Blazers",f17$pk)
 f17$pk<-gsub("公牛","Bulls",f17$pk)
 f17$pk<-gsub("活塞","Pistons",f17$pk)
 f17$pk<-gsub("步行者","Pacers",f17$pk)
 f17$pk<-gsub("爵士","Jazz",f17$pk)
 f17$pk<-gsub("骑士","Cavaliers",f17$pk)
 
 f17$vs_team<-gsub("小牛","Mavericks",f17$vs_team)
 f17$vs_team<-gsub("独行侠","Mavericks",f17$vs_team)
 f17$vs_team<-gsub("黄蜂","Hornets",f17$vs_team)
 f17$vs_team<-gsub("七六人","76ers",f17$vs_team)
 f17$vs_team<-gsub("尼克斯","Knicks",f17$vs_team)
 f17$vs_team<-gsub("奇才","Wizards",f17$vs_team)
 f17$vs_team<-gsub("火箭","Rockets",f17$vs_team)
 f17$vs_team<-gsub("热火","Heat",f17$vs_team)
 
 
 f17$vs_team<-gsub("湖人","Lakers",f17$vs_team)
 f17$vs_team<-gsub("凯尔特","Celtics",f17$vs_team)
 f17$vs_team<-gsub("太阳","Suns",f17$vs_team)
 f17$vs_team<-gsub("森林狼","Timberwolves",f17$vs_team)
 f17$vs_team<-gsub("鹈鹕","Pelicans",f17$vs_team)
 f17$vs_team<-gsub("掘金","Nuggets",f17$vs_team)
 f17$vs_team<-gsub("太阳","Suns",f17$vs_team)
 f17$vs_team<-gsub("猛龙","Raptors",f17$vs_team)
 f17$vs_team<-gsub("雄鹿","Bucks",f17$vs_team)
 f17$vs_team<-gsub("雷霆","Thunder",f17$vs_team)
 f17$vs_team<-gsub("老鹰","Hawks",f17$vs_team)
 f17$vs_team<-gsub("国王","Kings",f17$vs_team)
 f17$vs_team<-gsub("公牛","Bulls",f17$vs_team)
 f17$vs_team<-gsub("掘金","Nuggets",f17$vs_team)
 f17$vs_team<-gsub("灰熊","Grizzlies",f17$vs_team)
 f17$vs_team<-gsub("活塞","Pistons",f17$vs_team)
 f17$vs_team<-gsub("掘金","Nuggets",f17$vs_team)
 f17$vs_team<-gsub("篮网","Nets",f17$vs_team)
 f17$vs_team<-gsub("老鹰","Hawks",f17$vs_team)
 f17$vs_team<-gsub("76人","76ers",f17$vs_team)
 f17$vs_team<-gsub("快船","Clippers",f17$vs_team)
 f17$vs_team<-gsub("猛龙","Raptors",f17$vs_team)
 f17$vs_team<-gsub("国王","Kings",f17$vs_team)
 f17$vs_team<-gsub("马刺","Spurs",f17$vs_team)
 f17$vs_team<-gsub("灰熊","Grizzlies",f17$vs_team)
 f17$vs_team<-gsub("湖人","Lakers",f17$vs_team)
 f17$vs_team<-gsub("太阳","Suns",f17$vs_team)
 f17$vs_team<-gsub("雄鹿","Bucks",f17$vs_team)
 f17$vs_team<-gsub("勇士","Warriors",f17$vs_team)
 f17$vs_team<-gsub("快船","Clippers",f17$vs_team)
 f17$vs_team<-gsub("魔术","Magic",f17$vs_team)
 f17$vs_team<-gsub("篮网","Nets",f17$vs_team)
 f17$vs_team<-gsub("凯尔特","Celtics",f17$vs_team)
 f17$vs_team<-gsub("开拓者","Blazers",f17$vs_team)
 f17$vs_team<-gsub("公牛","Bulls",f17$vs_team)
 f17$vs_team<-gsub("活塞","Pistons",f17$vs_team)
 f17$vs_team<-gsub("步行者","Pacers",f17$vs_team)
 f17$vs_team<-gsub("爵士","Jazz",f17$vs_team)
 f17$vs_team<-gsub("骑士","Cavaliers",f17$vs_team)
 f17$vs_team<-gsub("[\u4e00-\u9fa5]","",f17$vs_team)
 
 
 f17$player<-gsub("空","no rookie",f17$player)
 f17$player<-gsub("本西蒙斯","Ben Simmons",f17$player)
 f17$player<-gsub("布兰顿英格拉姆","Brandon Ingram",f17$player)
 f17$player<-gsub("杰伦布朗","Jaylen Brown",f17$player)
 f17$player<-gsub("德拉甘·本德尔","Dragan Bender",f17$player)
 f17$player<-gsub("克里斯邓恩","Kris Dunn",f17$player)
 f17$player<-gsub("巴迪希尔德","Buddy Hield",f17$player)
 f17$player<-gsub("贾马尔穆雷","Jamal Murray",f17$player)
 f17$player<-gsub("马基斯克里斯","Marquese Chriss",f17$player)
 f17$player<-gsub("雅各布珀尔特尔","Jakob Poeltl",f17$player)
 f17$player<-gsub("索恩马克","Thon Maker",f17$player)
 f17$player<-gsub("多曼塔斯萨博尼斯","Domantas Sabonis",f17$player)
 f17$player<-gsub("陶林普林斯","Taurean Prince",f17$player)
 f17$player<-gsub("乔治斯帕帕扬尼斯","Georgios Papagiannis",f17$player)
 f17$player<-gsub("丹泽尔瓦伦蒂内","Denzel Valentine",f17$player)
 f17$player<-gsub("胡安埃尔南戈麦斯","Juancho Hernangomez",f17$player)
 f17$player<-gsub("盖尔雄亚布塞莱","Guerschon Yabusele",f17$player)
 f17$player<-gsub("韦德鲍德温","Wade Baldwin IV",f17$player)
 f17$player<-gsub("亨利埃伦森","Henry Ellenson",f17$player)
 f17$player<-gsub("马里克比斯利","Malik Beasley",f17$player)
 f17$player<-gsub("卡里斯勒夫特","Caris LeVert",f17$player)
 f17$player<-gsub("德安德烈本布里","DeAndre' Bembry",f17$player)
 f17$player<-gsub("马拉奇理查德森","Malachi Richardson",f17$player)
 f17$player<-gsub("安特日日奇","Ante Zizic",f17$player)
 f17$player<-gsub("蒂莫西鲁瓦乌","Timothe Luwawu-Cabarrot",f17$player)
 f17$player<-gsub("富尔坎科尔克马兹","Furkan Korkmaz",f17$player)
 f17$player<-gsub("帕斯卡尔西亚卡姆","Pascal Siakam",f17$player)
 f17$player<-gsub("斯卡尔拉比西埃","Skal Labissiere",f17$player)
 f17$player<-gsub("德章泰穆雷","Dejounte Murray",f17$player)
 f17$player<-gsub("德扬泰戴维斯","Deyonta Davis",f17$player)
 f17$player<-gsub("伊维察祖巴茨","Ivica Zubac",f17$player)
 f17$player<-gsub("谢赫迪亚洛","Cheick Diallo",f17$player)
 f17$player<-gsub("泰勒尤利斯","Tyler Ulis",f17$player)
 f17$player<-gsub("马尔科姆布罗格登","Malcolm Brogdon",f17$player)
 f17$player<-gsub("帕特里克麦考","Patrick McCaw",f17$player)
 f17$player<-gsub("周琦","Zhou Qi",f17$player)
 f17$player<-gsub("杰克莱曼","Jake Layman",f17$player)
 f17$player<-gsub("保罗齐普泽","Paul Zipser",f17$player)
 f17$player<-gsub("阿卜杜勒纳迪尔","Abdel Nader",f17$player)
 f17$player<-gsub("蒂龙华莱士","Tyrone Wallace",f17$player)
 
 
 write.csv(f17,"c:/users/lenovo/desktop/BALL/JSM投稿/data and code/f17_E.csv")
 
 