library(plyr)
library(xlsx)
library(tcltk)
library(progress)
library(plyr)
library(magrittr)  
library(mice)      #处理缺失值
library(xts)
library(rJava)
library(xlsxjars)

f16<-read.csv("c:/users/lenovo/desktop/BALL/JSM投稿/data and code/final16.csv")
# f16s<-f16[,c(2,3,11,25,75)]
# head(f16s)

#name<-read.csv("c:/users/lenovo/desktop/BALL/JSM投稿/data and code/f16.csv")

#替换team
# a<-paste("f16s$team1<-gsub(\"",name$team16,"\",\"",name$team,"\",f16s$team1)",sep="")%>%as.data.frame()
# b<-paste("f16s$pk<-gsub(\"",name$team16,"\",\"",name$team,"\",f16s$pk)",sep="")%>%as.data.frame()
# c<-paste("f16s$vs_team<-gsub(\"",name$team16,"\",\"",name$team,"\",f16s$vs_team)",sep="")%>%as.data.frame()
# #替换人名
# d<-paste("f16s$player<-gsub(\"",name$player16,"\",\"",name$player,"\",f16s$player)",sep="")%>%as.data.frame()
# 
# e<-rbind(a,b,c,d)
# write.csv(e,"c:/users/lenovo/desktop/BALL/JSM投稿/data and code/Eng_N_16.csv")


f16$team1<-gsub("小牛","Mavericks",f16$team1)
f16$team1<-gsub("独行侠","Mavericks",f16$team1)
f16$team1<-gsub("黄蜂","Hornets",f16$team1)
f16$team1<-gsub("七六人","76ers",f16$team1)
f16$team1<-gsub("尼克斯","Knicks",f16$team1)
f16$team1<-gsub("奇才","Wizards",f16$team1)
f16$team1<-gsub("火箭","Rockets",f16$team1)
f16$team1<-gsub("热火","Heat",f16$team1)

f16$team1<-gsub("湖人","Lakers",f16$team1)
f16$team1<-gsub("凯尔特","Celtics",f16$team1)
f16$team1<-gsub("太阳","Suns",f16$team1)
f16$team1<-gsub("森林狼","Timberwolves",f16$team1)
f16$team1<-gsub("鹈鹕","Pelicans",f16$team1)
f16$team1<-gsub("掘金","Nuggets",f16$team1)
f16$team1<-gsub("太阳","Suns",f16$team1)
f16$team1<-gsub("猛龙","Raptors",f16$team1)
f16$team1<-gsub("雄鹿","Bucks",f16$team1)
f16$team1<-gsub("雷霆","Thunder",f16$team1)
f16$team1<-gsub("老鹰","Hawks",f16$team1)
f16$team1<-gsub("国王","Kings",f16$team1)
f16$team1<-gsub("公牛","Bulls",f16$team1)
f16$team1<-gsub("掘金","Nuggets",f16$team1)
f16$team1<-gsub("灰熊","Grizzlies",f16$team1)
f16$team1<-gsub("活塞","Pistons",f16$team1)
f16$team1<-gsub("掘金","Nuggets",f16$team1)
f16$team1<-gsub("篮网","Nets",f16$team1)
f16$team1<-gsub("老鹰","Hawks",f16$team1)
f16$team1<-gsub("76人","76ers",f16$team1)
f16$team1<-gsub("快船","Clippers",f16$team1)
f16$team1<-gsub("猛龙","Raptors",f16$team1)
f16$team1<-gsub("国王","Kings",f16$team1)
f16$team1<-gsub("马刺","Spurs",f16$team1)
f16$team1<-gsub("灰熊","Grizzlies",f16$team1)
f16$team1<-gsub("湖人","Lakers",f16$team1)
f16$team1<-gsub("太阳","Suns",f16$team1)
f16$team1<-gsub("雄鹿","Bucks",f16$team1)
f16$team1<-gsub("勇士","Warriors",f16$team1)
f16$team1<-gsub("快船","Clippers",f16$team1)
f16$team1<-gsub("魔术","Magic",f16$team1)
f16$team1<-gsub("篮网","Nets",f16$team1)
f16$team1<-gsub("凯尔特","Celtics",f16$team1)
f16$team1<-gsub("开拓者","Blazers",f16$team1)
f16$team1<-gsub("公牛","Bulls",f16$team1)
f16$team1<-gsub("活塞","Pistons",f16$team1)
f16$team1<-gsub("步行者","Pacers",f16$team1)
f16$team1<-gsub("爵士","Jazz",f16$team1)
f16$team1<-gsub("骑士","Cavaliers",f16$team1)

f16$pk<-gsub("小牛","Mavericks",f16$pk)
f16$pk<-gsub("独行侠","Mavericks",f16$pk)
f16$pk<-gsub("黄蜂","Hornets",f16$pk)
f16$pk<-gsub("七六人","76ers",f16$pk)
f16$pk<-gsub("尼克斯","Knicks",f16$pk)
f16$pk<-gsub("奇才","Wizards",f16$pk)
f16$pk<-gsub("火箭","Rockets",f16$pk)
f16$pk<-gsub("热火","Heat",f16$pk)

f16$pk<-gsub("湖人","Lakers",f16$pk)
f16$pk<-gsub("凯尔特","Celtics",f16$pk)
f16$pk<-gsub("太阳","Suns",f16$pk)
f16$pk<-gsub("森林狼","Timberwolves",f16$pk)
f16$pk<-gsub("鹈鹕","Pelicans",f16$pk)
f16$pk<-gsub("掘金","Nuggets",f16$pk)
f16$pk<-gsub("太阳","Suns",f16$pk)
f16$pk<-gsub("猛龙","Raptors",f16$pk)
f16$pk<-gsub("雄鹿","Bucks",f16$pk)
f16$pk<-gsub("雷霆","Thunder",f16$pk)
f16$pk<-gsub("老鹰","Hawks",f16$pk)
f16$pk<-gsub("国王","Kings",f16$pk)
f16$pk<-gsub("公牛","Bulls",f16$pk)
f16$pk<-gsub("掘金","Nuggets",f16$pk)
f16$pk<-gsub("灰熊","Grizzlies",f16$pk)
f16$pk<-gsub("活塞","Pistons",f16$pk)
f16$pk<-gsub("掘金","Nuggets",f16$pk)
f16$pk<-gsub("篮网","Nets",f16$pk)
f16$pk<-gsub("老鹰","Hawks",f16$pk)
f16$pk<-gsub("76人","76ers",f16$pk)
f16$pk<-gsub("快船","Clippers",f16$pk)
f16$pk<-gsub("猛龙","Raptors",f16$pk)
f16$pk<-gsub("国王","Kings",f16$pk)
f16$pk<-gsub("马刺","Spurs",f16$pk)
f16$pk<-gsub("灰熊","Grizzlies",f16$pk)
f16$pk<-gsub("湖人","Lakers",f16$pk)
f16$pk<-gsub("太阳","Suns",f16$pk)
f16$pk<-gsub("雄鹿","Bucks",f16$pk)
f16$pk<-gsub("勇士","Warriors",f16$pk)
f16$pk<-gsub("快船","Clippers",f16$pk)
f16$pk<-gsub("魔术","Magic",f16$pk)
f16$pk<-gsub("篮网","Nets",f16$pk)
f16$pk<-gsub("凯尔特","Celtics",f16$pk)
f16$pk<-gsub("开拓者","Blazers",f16$pk)
f16$pk<-gsub("公牛","Bulls",f16$pk)
f16$pk<-gsub("活塞","Pistons",f16$pk)
f16$pk<-gsub("步行者","Pacers",f16$pk)
f16$pk<-gsub("爵士","Jazz",f16$pk)
f16$pk<-gsub("骑士","Cavaliers",f16$pk)

f16$vs_team<-gsub("小牛","Mavericks",f16$vs_team)
f16$vs_team<-gsub("独行侠","Mavericks",f16$vs_team)
f16$vs_team<-gsub("黄蜂","Hornets",f16$vs_team)
f16$vs_team<-gsub("七六人","76ers",f16$vs_team)
f16$vs_team<-gsub("尼克斯","Knicks",f16$vs_team)
f16$vs_team<-gsub("奇才","Wizards",f16$vs_team)
f16$vs_team<-gsub("火箭","Rockets",f16$vs_team)
f16$vs_team<-gsub("热火","Heat",f16$vs_team)


f16$vs_team<-gsub("湖人","Lakers",f16$vs_team)
f16$vs_team<-gsub("凯尔特","Celtics",f16$vs_team)
f16$vs_team<-gsub("太阳","Suns",f16$vs_team)
f16$vs_team<-gsub("森林狼","Timberwolves",f16$vs_team)
f16$vs_team<-gsub("鹈鹕","Pelicans",f16$vs_team)
f16$vs_team<-gsub("掘金","Nuggets",f16$vs_team)
f16$vs_team<-gsub("太阳","Suns",f16$vs_team)
f16$vs_team<-gsub("猛龙","Raptors",f16$vs_team)
f16$vs_team<-gsub("雄鹿","Bucks",f16$vs_team)
f16$vs_team<-gsub("雷霆","Thunder",f16$vs_team)
f16$vs_team<-gsub("老鹰","Hawks",f16$vs_team)
f16$vs_team<-gsub("国王","Kings",f16$vs_team)
f16$vs_team<-gsub("公牛","Bulls",f16$vs_team)
f16$vs_team<-gsub("掘金","Nuggets",f16$vs_team)
f16$vs_team<-gsub("灰熊","Grizzlies",f16$vs_team)
f16$vs_team<-gsub("活塞","Pistons",f16$vs_team)
f16$vs_team<-gsub("掘金","Nuggets",f16$vs_team)
f16$vs_team<-gsub("篮网","Nets",f16$vs_team)
f16$vs_team<-gsub("老鹰","Hawks",f16$vs_team)
f16$vs_team<-gsub("76人","76ers",f16$vs_team)
f16$vs_team<-gsub("快船","Clippers",f16$vs_team)
f16$vs_team<-gsub("猛龙","Raptors",f16$vs_team)
f16$vs_team<-gsub("国王","Kings",f16$vs_team)
f16$vs_team<-gsub("马刺","Spurs",f16$vs_team)
f16$vs_team<-gsub("灰熊","Grizzlies",f16$vs_team)
f16$vs_team<-gsub("湖人","Lakers",f16$vs_team)
f16$vs_team<-gsub("太阳","Suns",f16$vs_team)
f16$vs_team<-gsub("雄鹿","Bucks",f16$vs_team)
f16$vs_team<-gsub("勇士","Warriors",f16$vs_team)
f16$vs_team<-gsub("快船","Clippers",f16$vs_team)
f16$vs_team<-gsub("魔术","Magic",f16$vs_team)
f16$vs_team<-gsub("篮网","Nets",f16$vs_team)
f16$vs_team<-gsub("凯尔特","Celtics",f16$vs_team)
f16$vs_team<-gsub("开拓者","Blazers",f16$vs_team)
f16$vs_team<-gsub("公牛","Bulls",f16$vs_team)
f16$vs_team<-gsub("活塞","Pistons",f16$vs_team)
f16$vs_team<-gsub("步行者","Pacers",f16$vs_team)
f16$vs_team<-gsub("爵士","Jazz",f16$vs_team)
f16$vs_team<-gsub("骑士","Cavaliers",f16$vs_team)
f16$vs_team<-gsub("[\u4e00-\u9fa5]","",f16$vs_team)

f16$player<-gsub("无","no rookie",f16$player)
f16$player<-gsub("布兰顿-英格拉姆","Brandon Ingram",f16$player)
f16$player<-gsub("杰伦-布朗","Jaylen Brown",f16$player)
f16$player<-gsub("德拉甘·本德尔","Dragan Bender",f16$player)
f16$player<-gsub("克里斯-邓恩","Kris Dunn",f16$player)
f16$player<-gsub("巴迪-希尔德","Buddy Hield",f16$player)
f16$player<-gsub("贾马尔-穆雷","Jamal Murray",f16$player)
f16$player<-gsub("马基斯-克里斯","Marquese Chriss",f16$player)
f16$player<-gsub("雅各布-珀尔特尔","Jakob Poeltl",f16$player)
f16$player<-gsub("索恩-马克","Thon Maker",f16$player)
f16$player<-gsub("多曼塔斯-萨博尼斯","Domantas Sabonis",f16$player)
f16$player<-gsub("陶林-普林斯","Taurean Prince",f16$player)
f16$player<-gsub("乔治斯-帕帕扬尼斯","Georgios Papagiannis",f16$player)
f16$player<-gsub("丹泽尔-瓦伦蒂内","Denzel Valentine",f16$player)
f16$player<-gsub("胡安-埃尔南戈麦斯","Juancho Hernangomez",f16$player)
f16$player<-gsub("韦德-鲍德温","Wade Baldwin IV",f16$player)
f16$player<-gsub("亨利-埃伦森","Henry Ellenson",f16$player)
f16$player<-gsub("马里克-比斯利","Malik Beasley",f16$player)
f16$player<-gsub("卡里斯-勒夫特","Caris LeVert",f16$player)
f16$player<-gsub("德安德烈-本布里","DeAndre' Bembry",f16$player)
f16$player<-gsub("蒂莫西-鲁瓦乌","Timothe Luwawu",f16$player)
f16$player<-gsub("布莱斯-约翰逊","Brice Johnson",f16$player)
f16$player<-gsub("帕斯卡尔-西亚卡姆","Pascal Siakam",f16$player)
f16$player<-gsub("斯卡尔-拉比西埃","Skal Labissiere",f16$player)
f16$player<-gsub("德章泰-穆雷","Dejounte Murray",f16$player)
f16$player<-gsub("德扬泰-戴维斯","Deyonta Davis",f16$player)
f16$player<-gsub("伊维察-祖巴茨","Ivica Zubac",f16$player)
f16$player<-gsub("泰勒-尤利斯","Tyler Ulis",f16$player)
f16$player<-gsub("马尔科姆-布罗格登","Malcolm Brogdon",f16$player)
f16$player<-gsub("帕特里克-麦考","Patrick McCaw",f16$player)
f16$player<-gsub("戴蒙得-斯通","Diamond Stone",f16$player)
f16$player<-gsub("斯蒂芬-齐默尔曼","Stephen Zimmerman",f16$player)
f16$player<-gsub("伊塞亚-怀特海德","Isaiah Whitehead",f16$player)
f16$player<-gsub("迪米特里厄斯-杰克逊","Demetrius Jackson",f16$player)
f16$player<-gsub("杰克-莱曼","Jake Layman",f16$player)
f16$player<-gsub("保罗-齐普泽","Paul Zipser",f16$player)
f16$player<-gsub("迈克尔-贝纳杰","Michael Gbinije",f16$player)
f16$player<-gsub("乔治-尼昂","Georges Niang",f16$player)
f16$player<-gsub("乔尔-博伦博伊","Joel Bolomboy",f16$player)
f16$player<-gsub("凯-费尔德","Kay Felder",f16$player)

write.csv(f16,"c:/users/lenovo/desktop/BALL/JSM投稿/data and code/f16_E.csv")

